"""
VEGA Orchestrator Configuration — [PROJECT_NAME]

Generated by /vega-init on [DEPLOY_DATE].
Project addendum: framework/VEGA_[PROJECT_NAME]_Project_Addendum.md
"""

import os
from pathlib import Path

# ─── Project identity ────────────────────────────────────────────────────────
PROJECT_NAME = "[PROJECT_NAME]"
DEPLOY_DATE = "[DEPLOY_DATE]"

# ─── Paths ───────────────────────────────────────────────────────────────────
BASE_DIR = Path(__file__).resolve().parent.parent
AGENTS_DIR = str(BASE_DIR / "agents")
UNIVERSAL_DIR = str(BASE_DIR / "universal")
SCOPE_DIR = str(BASE_DIR / "scope")
FRAMEWORK_DIR = str(BASE_DIR / "framework")
ARTIFACTS_DIR = str(BASE_DIR / "artifacts" / "archive")
CYCLES_DIR = str(BASE_DIR / "cycles" / "active")
OP_BACKLOG_DIR = str(BASE_DIR / "op_backlog")
ADMIN_BACKLOG_DIR = str(BASE_DIR / "admin_backlog")   # Spec v5 §2 — GOV + role requests
STATE_DIR = str(BASE_DIR / "state")
TEST_MODELS_FULL_DIR = str(BASE_DIR / "test_models" / "full")
TEST_MODELS_BUILD_DIR = str(BASE_DIR / "test_models" / "build")

# ─── Role-based access (Framework v6 §13, Spec v5 §10.4) ─────────────────────
CONFIG_DIR = str(BASE_DIR / "config")
ROLES_FILE = str(BASE_DIR / "config" / "roles.json")          # hashed tokens + telegram IDs
RECOVERY_FILE = str(BASE_DIR / "config" / "recovery.hash")    # break-glass key (hashed)
INVITES_DIR = str(BASE_DIR / "config" / "invites")            # pending invite codes
NOTIFICATIONS_FILE = str(BASE_DIR / "config" / "notifications.json")  # per-role prefs
ROLE_EVENTS_FILE = str(BASE_DIR / "state" / "role_events.jsonl")      # append-only audit trail
INVITE_EXPIRY = 24 * 60 * 60   # 24 hours
OTP_EXPIRY = 5 * 60            # 5 minutes

# ─── Agents ──────────────────────────────────────────────────────────────────
AGENTS = ["SG", "SA", "SE", "TG", "TA", "TE", "BR", "BTA", "SYS"]

# ─── Models ──────────────────────────────────────────────────────────────────
# Default model — verify against current Anthropic API docs at deployment time.
AGENT_MODEL = "claude-sonnet-4-6"

# Per-agent overrides. Mutable at runtime via /model command.
AGENT_MODEL_OVERRIDES = {
    "SG":  "claude-opus-4-7",     # Scope Guardian — judgment-heavy
    "TG":  "claude-opus-4-7",     # Tests Guardian — judgment-heavy
    "SE":  "claude-haiku-4-5",    # Scope Editor — mechanical edits
    "TE":  "claude-haiku-4-5",    # Tests Editor — mechanical edits
    # SA, TA, BR, BTA, SYS fall through to AGENT_MODEL
}

# ─── Extended thinking ───────────────────────────────────────────────────────
EXTENDED_THINKING_ENABLED = True
THINKING_BUDGET_TOKENS = 10000   # Per execution

# ─── Prompt caching ──────────────────────────────────────────────────────────
# Static content (system prompt + UNIVERSAL + wiki + scope) is cache_control'd
# so repeated calls within the cache TTL pay reduced input cost.
PROMPT_CACHING_ENABLED = True

MAX_TOKENS = 32000   # Per agent execution. Covers extended-thinking + output.
                     # The executor streams the API call, so this can exceed the
                     # non-streaming ~21k ceiling. 16000 was too small for Sonnet
                     # adaptive thinking on complex tasks (thinking ate the budget).

# ─── Polling ─────────────────────────────────────────────────────────────────
POLL_INTERVAL = 10   # Seconds between inbox checks

# ─── SYS scheduling ──────────────────────────────────────────────────────────
SYS_SCHEDULE = "daily"           # "daily" | "every_N_executions" | "hourly"
SYS_DAILY_TIME = "02:00"         # Local time, if SYS_SCHEDULE == "daily"
SYS_EXECUTION_THRESHOLD = 20     # If SYS_SCHEDULE == "every_N_executions"

# ─── Cycle context monitoring ────────────────────────────────────────────────
CYCLE_CONTEXT_WARNING = 0.4      # Warn when cycle context reaches 40% of window

# ─── Wiki replace_section thresholds ─────────────────────────────────────────
# Trigger SYS review when an agent does N replace_sections between SYS runs.
WIKI_REPLACE_THRESHOLD_DEFAULT = 10
WIKI_REPLACE_THRESHOLDS = {
    # Per-agent overrides, set by OP based on SYS recommendations via GOV.
    # Example: "SG": 15, "TA": 3
}

# ─── CORTEX add-on ───────────────────────────────────────────────────────────
CORTEX_ENABLED = False           # Off by default — turn on once wikis grow.
CORTEX_SCAN_THRESHOLD = 15       # Below this entry count, agents linear-scan.

# ─── External Build ──────────────────────────────────────────────────────────
EXT_BUILD_ENABLED = True

# ─── Validated-state snapshots (Spec v5 §7.5, SC-7) ──────────────────────────
# On each scope approval, export an immutable snapshot of scope + triggering
# artifacts + content hashes to durable storage OUTSIDE the orchestrator tree.
SNAPSHOT_ENABLED = True
SNAPSHOT_LOCAL_DIR = str(BASE_DIR.parent / "vega-snapshots")  # outside the deployment tree
SNAPSHOT_GIT_REMOTE = ""          # optional — e.g. "origin" to also commit+push

# ─── Telegram freeform exchange (Spec v5 §3.1) ───────────────────────────────
# Off by default: freeform OP↔SG / Admin-OP↔SYS dialogue happens via MCP
# vega_exchange. Quick commands (/approve, /reject, /modify, /request, /resolve)
# always work regardless of this flag.
TELEGRAM_EXCHANGE_ENABLED = False

# ─── Anthropic API ───────────────────────────────────────────────────────────
ANTHROPIC_API_KEY = os.environ.get("ANTHROPIC_API_KEY", "")

# ─── Telegram ────────────────────────────────────────────────────────────────
TELEGRAM_BOT_TOKEN = os.environ.get("TELEGRAM_BOT_TOKEN", "")
TELEGRAM_OP_CHAT_ID = os.environ.get("TELEGRAM_OP_CHAT_ID", "")

# ─── MCP server (Spec v5 §12.1-12.3) ─────────────────────────────────────────
# Role-scoped HTTP endpoint. Token determines which tools are visible.
MCP_ENABLED = True
MCP_PORT = 8420
